#! /bin/bash

# Wait until a given host is online (determined by ping) then execute the
# given command
#
# Usage:
# ./do-when-up HOST COMMAND...
#
# Example
# ./do-when-up 1.2.3.4 ssh 1.2.3.4

if [ $# -lt 2 ]; then
	echo "Usage:"
	echo "  ./do-when-up HOST COMMAND..."
	exit 1
fi

HOST=$1

echo "Waiting for $HOST to come online..."

false
while [ $? -ne 0 ]; do
	sleep 1
	ping -c 1 -W 1 $HOST >/dev/null
done

# It's up, do what we're told
${@:2}
