#!/usr/bin/env perl
#
# maybe - companion to /usr/bin/true and /usr/bin/false.
#
# In a similar vein to `true` and `false` the `maybe` command exits
# with a status code of zero or one, depending on a random number.
#
# It can be useful in scripts which need to test-failures, or which
# benefit from randomness.
#
# Example:
#    maybe && echo "I pass"
#    maybe || echo "I fail"
#
# This should be installed in your system location, eg /usr/bin/maybe.
#
# 08-Nov-2004	ver 1.00
#
# USAGE: maybe
#
# COPYRIGHT: Copyright (c) 2004 Brendan Gregg.
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software Foundation,
#  Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#  (http://www.gnu.org/copyleft/gpl.html)
#
# 08-Nov-2004	Brendan Gregg	Created this.

use strict;
use warnings;

#
#  Generate Value
#
my $maybe = rand(1);
$maybe = sprintf( "%.0f", $maybe );    # see "perldoc -q round"

#
#  Return Value
#
exit($maybe);

